# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
    ignore:
      - dependency-name: '@types/express'
        update-types: ['version-update:semver-major']
      - dependency-name: '@types/node'
        update-types: ['version-update:semver-major']
    groups:
      dev-dependencies:
        dependency-type: development
        applies-to: version-updates
        update-types:
          - minor
          - patch
      prod-dependencies:
        dependency-type: production
        applies-to: version-updates
        update-types:
          - minor
          - patch        

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    groups:
      actions-all:
        applies-to: version-updates
        update-types:
          - minor
          - patch

  - package-ecosystem: 'devcontainers' # See documentation for possible values
    directory: '/'
    schedule:
      interval: weekly
