changesetIgnorePatterns:
  - .github/**
  - .yarn/**

compressionLevel: mixed

enableGlobalCache: true

nodeLinker: pnp

packageExtensions:
  probot@*:
    dependencies:
      smee-client: '*'

patchFolder: ./.yarn/patches

pnpEnableEsmLoader: true

pnpUnpluggedFolder: ./.yarn/unplugged

preferInteractive: true

supportedArchitectures:
  cpu:
    - current
    - x64
    - arm64
  os:
    - current
    - darwin
    - linux
    - win32
