AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Security Alert Watcher GitHub App

################################
# Parameters
################################

Parameters:
  githubAppId:
    Description: The App ID of your GitHub app
    Type: String
  githubWebhookSecret:
    Description: The webhook secret of your GitHub app
    Type: String
  githubPrivateKey:
    Description: The private key of your GitHub app
    Type: String
    NoEcho: true
  githubOrg:
    Description: The organization where the app is registered
    Type: String
  githubHost:
    Description: The GitHub host name to use (api.github.com)
    Type: String
    Default: api.github.com
  githubProtocol:
    Description: The GitHub API protocol (https)
    Type: String
    Default: https
    AllowedValues:
      - http
      - https
  logLevel:
    Description: The logging level
    Type: String
    Default: info
    AllowedValues:
      - fatal
      - error
      - warn
      - info
      - debug

################################
# Global configurations
################################

Globals:
  Function:
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true


################################
# Resources
################################

Resources:

  SecurityWatcher:
    DependsOn:
      - SecurityWatcherLogGroup
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-webhook
      Description: Security watcher
      CodeUri: .
      Handler: index.securityWatcher
      FunctionUrlConfig:
        AuthType: NONE
      Runtime: nodejs20.x
      PackageType: Zip
      MemorySize: 256
      Timeout: 15
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: POST

      Environment:
        Variables:
          APP_ID: !Ref githubAppId
          WEBHOOK_SECRET: !Ref githubWebhookSecret
          PRIVATE_KEY: !Ref githubPrivateKey
          GH_ORG: !Ref githubOrg
          NODE_ENV: production
          GHE_HOST: !Ref githubHost
          GHE_PROTOCOL: !Ref githubProtocol
          LOG_LEVEL: !Ref logLevel
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Sourcemap: false
        Target: 'node20' # ES2022 support
        Format: esm
        OutExtension:
          - .js=.mjs
        #Banner:
        #  - js=import { createRequire } from 'module'; const require = createRequire(import.meta.url);
        EntryPoints:
          - dist/index.mjs
  SecurityWatcherLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${AWS::StackName}-webhook'
      RetentionInDays: 1
Outputs:
  WebhookUrl:
    Description: 'Webhook Endpoint URL'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
